language: go
go:
  - "1.11"
go_import_path: github.com/xen0n/go-workwx
branches:
  # https://bors.tech/documentation/getting-started/
  # unfortunately whitelisting is necessary because otherwise my own branches
  # would get (repeatedly) built as well...
  only:
    - 'staging'
    - 'trying'
    - 'develop'
    - 'master'
cache:
  - $GOPATH/pkg/dep
before_install:
  - go get -u -v github.com/golang/dep/cmd/dep
  - go get -u -v honnef.co/go/tools/cmd/staticcheck
install:
  - dep ensure -v
  - go install -v ./...
script:
  - ./ci/run-lint.sh
  - go test -v ./...
